name: Build and Test Hiking App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r FINALPROJECT/hiking_app/requirements.txt

    - name: Run tests
      run: |
        cd FINALPROJECT/hiking_app
        python manage.py test

